"""Матриця відповідності: пункт методички → правило → код → тест → схема → статус → вплив на рішення. Перевіряється тестом (код і тести існують), документ SMC_MATRIX.md генерується звідси.
Статус «СИНТЕТИКА»: реалізовано й перевірено на якісних фікстурах/властивостях; перевірка на реальних OHLCV (replay у worker) ще не виконана. Вплив на READY — лише SHADOW до погодження."""
from __future__ import annotations

from typing import Any, Dict, List

SYN = "СИНТЕТИКА (реальні OHLCV — replay у worker, ще не виконано)"
PART = "ЧАСТКОВО"
NOALGO = "НЕ АЛГОРИТМІЗОВАНО"
SH = "SHADOW: показ у картці/логу, READY не змінює"
BR = "Brain v2.1 без змін"

T_ST, T_LQ, T_IM, T_BL, T_SS, T_MD, T_GD, T_IN, T_RP = ("scripts/test_smc_structure.py", "scripts/test_smc_liquidity.py", "scripts/test_smc_imbalance.py", "scripts/test_smc_blocks.py",
                                                      "scripts/test_smc_sessions_pd_flow.py", "scripts/test_smc_models.py", "scripts/test_smc_golden.py", "scripts/test_smc_integration.py", "scripts/test_smc_replay.py")

ROWS: List[Dict[str, Any]] = [
    {"id": "R-STR-01", "section": "S09.2/S10.1", "rule": "Swing = 3 свічки: центр вищий/нижчий за обидві сусідні; підтвердження закриттям правої; 2 свічки без центру — не swing", "code": "office2.smc.structure.swings", "test": f"{T_ST}::test_swing_three_candles_and_negative", "images": [4], "status": SYN, "impact": SH, "brain": "частково (n=2, 5 свічок — D-05)"},
    {"id": "R-STR-02", "section": "S10.2/S10.3", "rule": "HH/HL/LH/LL/EQH/EQL за порівнянням з попереднім swing того ж типу", "code": "office2.smc.structure.label_swings", "test": f"{T_ST}::test_uptrend_bms_chain_and_labels", "images": [5, 6], "status": SYN, "impact": SH, "brain": "частково"},
    {"id": "R-STR-03", "section": "S09.3", "rule": "BMS = закриття тілом за структурним swing у напрямку тренду; структурний high = найвищий підтверджений swing після останнього зламу", "code": "office2.smc.structure.analyze", "test": f"{T_ST}::test_uptrend_bms_chain_and_labels", "images": [8], "status": SYN, "impact": SH, "brain": "немає (є простий displacement-зсув)"},
    {"id": "R-STR-04", "section": "S12", "rule": "MSS = закриття за захищеним мінімумом (початок останньої ноги) ПІСЛЯ останнього BMS; Confirm = перше оновлення в новому напрямку; MSS_FAILED при поверненні над вершину", "code": "office2.smc.structure.analyze", "test": f"{T_ST}::test_mss_then_confirm", "images": [9, 10], "status": SYN, "impact": SH, "brain": "частково"},
    {"id": "R-STR-05", "section": "S12", "rule": "Злам внутрішнього мінімуму (не початок останньої ноги) — корекція в межах розширення, НЕ MSS", "code": "office2.smc.structure.analyze", "test": f"{T_ST}::test_correction_break_is_not_mss", "images": [10, 11], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-STR-06", "section": "S10.4", "rule": "Range: ≥2 swing high і ≥2 swing low у допуску 1,5 ATR, висота ≥2 ATR; межі 0/1, EQ 0,5", "code": "office2.smc.structure.detect_range", "test": f"{T_ST}::test_range_and_deviation", "images": [7], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-STR-07", "section": "S10.4/S11", "rule": "Девіація (вихід + повернення ≤3 бари) vs прийнятий вихід (≥2 закриття) = expansion", "code": "office2.smc.structure.deviation_events", "test": f"{T_ST}::test_accepted_breakout_is_expansion_not_deviation", "images": [7], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-STR-08", "section": "S09.4/S08", "rule": "Синхронізація ТФ: пріоритет старшого; локальна корекція ≠ зміна старшої структури", "code": "office2.smc.structure.tf_sync", "test": f"{T_ST}::test_tf_sync_local_correction_vs_htf_change", "images": [], "status": SYN, "impact": SH, "brain": "є (HTF-карта, counter-trend gate)"},
    {"id": "R-STR-09", "section": "S06", "rule": "Фази ринку/Wyckoff накопичення-розподіл — гіпотеза, не детектор; спостережувані стани UP/DOWN/RANGE/TRANSITION реалізовано", "code": "office2.smc.structure.analyze", "test": f"{T_GD}::test_every_scheme_is_mapped_to_a_runnable_golden_check", "images": [1, 2, 3], "status": NOALGO, "impact": "—", "brain": "є (Wyckoff як EVIDENCE)"},
    {"id": "R-TF-01", "section": "S07/S08", "rule": "Три перспективи: LTP (W/D) → ITP (H1/M15) → STP (M5/M1). SMC читає D1/H4/H1/M15; STP M1/M5 для виконання входу НЕ інтегровано (M5 лишається EVIDENCE у Brain)", "code": "office2.smc.engine.analyze", "test": f"{T_MD}::test_reversal_long_full_sequence_ready", "images": [], "status": PART, "impact": SH, "brain": "є (HTF-карта MN→M15, M5 EVIDENCE)"},
    {"id": "R-LIQ-01", "section": "S15", "rule": "Пули: swing, EQH/EQL (допуск 0,15 ATR), межі range", "code": "office2.smc.liquidity.swing_levels", "test": f"{T_LQ}::test_eqh_eql_and_pools", "images": [15], "status": SYN, "impact": SH, "brain": "частково (levels PDH/H4SW…)"},
    {"id": "R-LIQ-02", "section": "S15", "rule": "PDH/PDL/PWH/PWL/PMH/PML лише від ПОПЕРЕДНЬОГО закритого періоду", "code": "office2.smc.liquidity.htf_levels", "test": f"{T_LQ}::test_htf_levels_previous_closed_period_only", "images": [], "status": SYN, "impact": SH, "brain": "є"},
    {"id": "R-LIQ-03", "section": "S15/S27", "rule": "Session High/Low завершених сесій (канонічні NY-вікна з DST)", "code": "office2.smc.sessions.session_levels", "test": f"{T_SS}::test_session_levels_known_after_session_end_only", "images": [], "status": SYN, "impact": SH, "brain": "є (власні вікна)"},
    {"id": "R-LIQ-04", "section": "S15", "rule": "Ліквідність за трендовою: проєкція лінії через 2 останні swing (наближення)", "code": "office2.smc.liquidity.trendline_levels", "test": f"{T_LQ}::test_eqh_eql_and_pools", "images": [15], "status": PART, "impact": SH, "brain": "немає"},
    {"id": "R-LIQ-05", "section": "S15", "rule": "External vs Internal liquidity відносно поточного range", "code": "office2.smc.liquidity.ie_class", "test": f"{T_LQ}::test_internal_vs_external_liquidity", "images": [15], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-LIQ-06", "section": "S15/S22", "rule": "Життєвий цикл рівня IDENTIFIED→APPROACHED→TOUCHED→SWEPT|ACCEPTED_BREAKOUT→RETESTED|INVALIDATED з перевіркою допустимих переходів", "code": "office2.smc.liquidity.track", "test": f"{T_LQ}::test_accepted_breakout_then_retest_then_invalidated", "images": [], "status": SYN, "impact": SH, "brain": "частково (prior closes_beyond)"},
    {"id": "R-LIQ-07", "section": "S22", "rule": "Raid/Sweep: FRESH_RAID, SFP, ACCEPTED_BREAKOUT, LATE_SWEEP (не свіжий), WICK_ONLY (шум), PENDING", "code": "office2.smc.liquidity.track", "test": f"{T_LQ}::test_late_sweep_after_prior_acceptance_is_not_fresh", "images": [32], "status": SYN, "impact": SH, "brain": "частково"},
    {"id": "R-LIQ-08", "section": "S23", "rule": "SFP: прокол swing і закриття назад на тому ж барі", "code": "office2.smc.liquidity.track", "test": f"{T_LQ}::test_sfp_same_bar_close_back", "images": [33], "status": SYN, "impact": SH, "brain": "частково"},
    {"id": "R-IMB-01", "section": "S14", "rule": "FVG з трьох свічок; ефективне ціноутворення (перекриття тіней) — не FVG", "code": "office2.smc.imbalance.fvgs", "test": f"{T_IM}::test_fvg_geometry_and_efficient_negative", "images": [13, 14], "status": SYN, "impact": SH, "brain": "є (FVG у зоні входу)"},
    {"id": "R-IMB-02", "section": "S14.1", "rule": "Рівні 0,25/0,5/0,75/FF, «повага» зони, тіла vs тіні (тінь через зону не ламає; закриття тілом за дальньою межею — ламає)", "code": "office2.smc.imbalance.fill_state", "test": f"{T_IM}::test_fill_levels_and_respect_wick_vs_body", "images": [13, 14], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-IMB-03", "section": "S14.2", "rule": "VI (OHLC-проксі), Liquidity Void, Opening Gap (24/7 крипто майже немає), BPR", "code": "office2.smc.imbalance.volume_imbalances", "test": f"{T_IM}::test_vi_void_gap_bpr", "images": [], "status": PART, "impact": SH, "brain": "немає"},
    {"id": "R-PD-01", "section": "S13", "rule": "Dealing range, EQ, Premium/Discount; застарілі якорі — stale", "code": "office2.smc.pd.dealing_range", "test": f"{T_SS}::test_pd_ote_and_stale_anchor", "images": [7, 12], "status": SYN, "impact": SH, "brain": "частково (premium/discount EVIDENCE)"},
    {"id": "R-PD-02", "section": "S13.1", "rule": "OTE 0,5/0,62/0,705/0,79 від ноги; OTE без POI/тригера — не вхід", "code": "office2.smc.pd.ote", "test": f"{T_GD}::g_ote_with_ob", "images": [12], "status": SYN, "impact": SH, "brain": "є (OTE 62–79%)"},
    {"id": "R-OF-01", "section": "S16", "rule": "Order Flow як структурний proxy (UP/DOWN + FVG не зламано); біржових агресорів не імітуємо", "code": "office2.smc.flow.order_flow", "test": f"{T_SS}::test_order_flow_and_hrlr_lrlr_proxy", "images": [16, 17], "status": PART, "impact": SH, "brain": "є (CVD/taker-delta EVIDENCE — реальні дані)"},
    {"id": "R-OF-02", "section": "S17", "rule": "HRLR/LRLR за ефективністю ходу й розворотами (proxy)", "code": "office2.smc.flow.path_resistance", "test": f"{T_SS}::test_order_flow_and_hrlr_lrlr_proxy", "images": [18], "status": PART, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-01", "section": "S18", "rule": "OB: остання протилежна свічка перед імпульсним поглинанням (закриття ТІЛОМ за high/low свічки); без поглинання — не OB", "code": "office2.smc.blocks.order_blocks_bull", "test": f"{T_BL}::test_bull_ob_requires_engulfing_and_mt_lifecycle", "images": [19, 20], "status": SYN, "impact": SH, "brain": "частково (OB у зоні входу)"},
    {"id": "R-BLK-02", "section": "S18.1", "rule": "Структура OB: wick / open / MT=50% тіла; режим wick (тіло<40%) або body; живий поки тіло не закріпилось за MT; тести лічаться", "code": "office2.smc.blocks.order_blocks_bull", "test": f"{T_BL}::test_ob_wick_mode_for_small_body_long_wicks", "images": [21, 22, 23], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-03", "section": "S18.1", "rule": "Фрактальність OB: блок HTF = серія M15", "code": "office2.smc.blocks.ob_fractal", "test": f"{T_BL}::test_ob_fractality_htf_candle_is_series_on_m15", "images": [], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-04", "section": "S18.2", "rule": "Агресивний (від POI) і консервативний (після підтвердження) вхід; READY лише консервативний", "code": "office2.smc.models.evaluate", "test": f"{T_MD}::test_aggressive_entry_is_shown_but_never_ready", "images": [22, 23], "status": SYN, "impact": SH, "brain": "є (консервативний)"},
    {"id": "R-BLK-05", "section": "S19", "rule": "Breaker: OB пробито імпульсом після зняття ліквідності + MSS; ретест", "code": "office2.smc.blocks.breakers_bull", "test": f"{T_BL}::test_breaker_vs_mitigation_profiles", "images": [24], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-06", "section": "S20", "rule": "Mitigation: два профілі MB_TEXT і MB_SCHEME (D-03), без «тихого злиття» з BB", "code": "office2.smc.blocks.breakers_bull", "test": f"{T_BL}::test_breaker_vs_mitigation_profiles", "images": [25, 26, 27], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-07", "section": "S21", "rule": "Rejection Block: довга тінь (≥50% діапазону, ≥0,5 ATR) через SSL/BSL з реакцією; MT тіні", "code": "office2.smc.blocks.rejection_blocks_bull", "test": f"{T_BL}::test_rejection_block_bull_wick_on_ssl", "images": [28, 29, 30, 31], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-08", "section": "S24", "rule": "StB/BtS: зняття SSL/BSL → MSS; зона = [екстремум raid, зламаний рівень MSS]; POI всередині", "code": "office2.smc.blocks.stb_bull", "test": f"{T_BL}::test_stb_zone_between_sweep_extreme_and_mss_level", "images": [34, 35, 36, 37], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-BLK-09", "section": "S25", "rule": "Sponsored Candle: два варіанти закриття тілом (D-04), неверифіковано", "code": "office2.smc.blocks.sponsored_bull", "test": f"{T_BL}::test_sponsored_two_variants_unverified", "images": [38], "status": PART, "impact": SH, "brain": "немає"},
    {"id": "R-MDL-01", "section": "S26", "rule": "Reversal (LONG/SHORT): контекст HTF → RAID → MS → POI → ретрейс → тригер → SL/цілі; хронологія обов'язкова; без HTF-контексту проти старшої структури — не береться", "code": "office2.smc.models.evaluate", "test": f"{T_MD}::test_reversal_long_full_sequence_ready", "images": [39, 40], "status": SYN, "impact": SH, "brain": "частково (sweep→зсув→ретрейс→тригер)"},
    {"id": "R-MDL-02", "section": "S26", "rule": "Continuation: bias HTF + RAID + MS1 + MS2 («2 MS») + POI + ретрейс + тригер", "code": "office2.smc.models.evaluate", "test": f"{T_MD}::test_continuation_needs_two_ms_and_aligned_bias", "images": [40], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-MDL-03", "section": "S26", "rule": "SHORT = точне дзеркало LONG (симетрія перевірена)", "code": "office2.smc.engine.analyze", "test": f"{T_MD}::test_reversal_short_is_mirror_of_long", "images": [39, 40], "status": SYN, "impact": SH, "brain": "є"},
    {"id": "R-SES-01", "section": "S27", "rule": "Killzones/optimal time: source-clock «UTC+3/KZ» зберігається окремо від канонічних NY-вікон з DST; торгового gate немає (D-02)", "code": "office2.smc.sessions.window_view", "test": f"{T_SS}::test_source_vs_canonical_windows_are_separate_and_not_a_gate", "images": [], "status": SYN, "impact": "—", "brain": "є (власні сесії)"},
    {"id": "R-SES-02", "section": "S29", "rule": "NYM = північ Нью-Йорка (America/New_York, DST), а не фіксовані 08:00; Київ першим, UTC у дужках", "code": "office2.smc.sessions.nym_utc", "test": f"{T_SS}::test_nym_follows_us_dst_not_fixed_0800", "images": [], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-SES-03", "section": "S29", "rule": "Judas Swing відносно NYM: FORMING → JUDAS → CONFIRMED, лише закриті бари", "code": "office2.smc.sessions.judas", "test": f"{T_SS}::test_judas_bear_forming_judas_confirmed", "images": [], "status": SYN, "impact": SH, "brain": "немає"},
    {"id": "R-SES-04", "section": "S28", "rule": "PO3/AMD: діапазон Азії (проксі) → маніпуляція → розподіл", "code": "office2.smc.sessions.amd", "test": f"{T_SS}::test_amd_manipulation_then_distribution", "images": [], "status": PART, "impact": SH, "brain": "немає"},
    {"id": "R-RSK-01", "section": "S05", "rule": "Ризик 0,5–1%/угоду, стоп після 2 SL, тижневий ліміт — portfolio_gate Brain; SMC SL/цілі рахуються тими ж brain.targets_for і порогами (MIN_STOP_ATR15, MIN_TP1_R)", "code": "office2.smc.engine._finalize", "test": f"{T_MD}::test_reversal_long_full_sequence_ready", "images": [], "status": SYN, "impact": BR, "brain": "є"},
    {"id": "R-INT-01", "section": "інтеграція", "rule": "SMC shadow у фоні не затримує Brain/Telegram, помилка SMC не ламає READY, рішення Brain побітово ті самі з SMC і без", "code": "office2.smc.shadow.run_cycle", "test": f"{T_IN}::test_smc_does_not_change_brain_decision", "images": [], "status": SYN, "impact": SH, "brain": "—"},
    {"id": "R-INT-02", "section": "інтеграція", "rule": "Знімок READY зберігає display-поле smc (overlay на свічках, кроки ✓/✗, збіг з Brain); Mini App малює шар SMC", "code": "office2.smc.overlay.build", "test": f"{T_IN}::test_smc_does_not_change_brain_decision", "images": [], "status": SYN, "impact": SH, "brain": "—"},
    {"id": "R-INT-03", "section": "інтеграція", "rule": "Time-frozen replay Brain vs SMC на однакових барах; R, хибні READY, recall пропущених рухів", "code": "office2.smc.replay.replay_arrays", "test": f"{T_RP}::test_replay_finds_smc_ready_exactly_when_sequence_completes_and_not_before", "images": [], "status": SYN, "impact": "—", "brain": "є (replay_at — одне рішення)"},
    {"id": "R-SRC-01", "section": "PDF Strong Candle Tester", "rule": "PDF = опис індикатора TradingView (Volume Delta, Supertrend, Fibonacci-сітка); формул «сильної свічки» не розкрито — вигадувати не можна; Strong Candle лишається EVIDENCE", "code": "office2.strongcandle.detect", "test": f"{T_GD}::test_sources_cover_all_toc_sections_and_discrepancies", "images": [], "status": NOALGO, "impact": BR, "brain": "є (sc-ours-1, EVIDENCE)"},
    {"id": "R-SRC-02", "section": "S01–S04, S30, S31", "rule": "Освітній/мотиваційний контекст, реклама, посилання на відео — не алгоритмізується; відео/статті за посиланнями недоступні й не вважаються прочитаними", "code": "office2.smc.sources.SECTIONS", "test": f"{T_GD}::test_sources_cover_all_toc_sections_and_discrepancies", "images": [1], "status": NOALGO, "impact": "—", "brain": "—"},
]


def render_md() -> str:
    from office2.smc import sources as SRC

    lines = ["# SMC: матриця відповідності (генерується з `office2/smc/matrix.py`)", "",
             "Пункт методички SM Trader → правило → код → тест → схема → статус → вплив на рішення. **Усі детектори зараз у режимі SHADOW: живі READY не змінено.** "
             "Статус «СИНТЕТИКА» означає: правило реалізовано й перевірено на якісних фікстурах за схемами та на властивостях (без lookahead, дзеркальна симетрія LONG/SHORT, випадкові ряди), "
             "але на реальних OHLCV ще не перевірено (потрібен replay у worker з доступом до біржі). Жодних тверджень про прибутковість.", "",
             "| Правило | Розділ | Що саме | Код | Тест | Схеми | Статус | Вплив на рішення | Brain v2.1 |", "|---|---|---|---|---|---|---|---|---|"]
    for r in ROWS:
        imgs = ", ".join(str(i) for i in r["images"]) or "—"
        lines.append(f"| {r['id']} | {r['section']} | {r['rule']} | `{r['code']}` | `{r['test']}` | {imgs} | {r['status']} | {r['impact']} | {r['brain']} |")
    lines += ["", "## Схеми (40 із «41»)", "", "| № | Схема | Розділ | Фікстура | Примітка |", "|---|---|---|---|---|"]
    for i in SRC.IMAGES:
        lines.append(f"| {i['n']} | {i['title']} | {i['section']} | {i.get('fixture') or '—'} | {i.get('note', '')} |")
    lines += ["", "## Розбіжності джерела (зафіксовано, не вирішено мовчки)", ""]
    for d in SRC.DISCREPANCIES:
        lines += [f"- **{d['id']}** ({d['where']}): {d['what']} → {d['decision']}"]
    lines += ["", "## Розділи джерела", "", "| ID | Заголовок | Клас | Примітка |", "|---|---|---|---|"]
    for s in SRC.SECTIONS:
        lines.append(f"| {s['id']} | {s['title']} | {s['cls']} | {s.get('note', '')} |")
    return "\n".join(lines) + "\n"
